# Nixpacks Configuration for LOL Chess Monorepo
# Deploy via Dokploy
# Set APP_TYPE environment variable to "backend" or "frontend"

[phases.setup]
# Use Node.js 22 (matching your fnm use v22 requirement)
nixPkgs = ["nodejs_22", "python3"]

[phases.install]
# Install all dependencies (workspace aware)
cmds = [
    "npm ci"
]

[phases.build]
# Build based on APP_TYPE environment variable
cmds = [
    '''
    if [ "$APP_TYPE" = "frontend" ]; then
        echo "Building frontend..."
        npm run build --workspace=apps/frontend
    elif [ "$APP_TYPE" = "backend" ]; then
        echo "Building backend..."
        npm run build --workspace=apps/backend
    else
        echo "Building both backend and frontend..."
        npm run build --workspace=apps/backend
        npm run build --workspace=apps/frontend
    fi
    '''
]

[start]
# Start command based on APP_TYPE
cmd = '''
if [ "$APP_TYPE" = "frontend" ]; then
    echo "Starting frontend with static file server..."
    npx serve -s apps/frontend/dist -l 3000
elif [ "$APP_TYPE" = "backend" ]; then
    echo "Starting backend..."
    node apps/backend/dist/main.js
else
    echo "Starting backend (default)..."
    node apps/backend/dist/main.js
fi
'''


# You'll need to set these in Dokploy's environment variables section:
# - APP_TYPE: "backend" or "frontend" (determines what to build/run)
# - MONGODB_URI: MongoDB connection string (backend only)
# - JWT_SECRET: JWT secret for authentication (backend only)
# - REDIS_HOST: Redis host (backend only, optional)
# - REDIS_PORT: Redis port (backend only, optional)
# - FRONTEND_URL: Your frontend URL for CORS (backend only)
# - VITE_API_URL: Backend API URL (frontend only)
